# Generated by Django 3.0.6 on 2023-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('url', models.CharField(max_length=1000, verbose_name='Link del video')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Espiritual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('url', models.CharField(max_length=1000, verbose_name='Link del video')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Inteligencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('url', models.CharField(max_length=1000, verbose_name='Link del video')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('url', models.CharField(max_length=1000, verbose_name='Link del video')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
    ]
