# Generated by Django 3.0.6 on 2023-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendiciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salud',
            name='video_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del video'),
        ),
    ]
