# Generated by Django 3.0.6 on 2023-12-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bendiciones', '0002_salud_video_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academia',
        ),
        migrations.DeleteModel(
            name='Espiritual',
        ),
        migrations.DeleteModel(
            name='Inteligencia',
        ),
    ]
