# Generated by Django 3.0.6 on 2023-12-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendiciones', '0003_auto_20231217_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='salud',
            name='tipo',
            field=models.CharField(choices=[('EJERCICIO', 'EJERCICIO'), ('NUTRICION', 'NUTRICION')], default='EJERCICIO', max_length=10, verbose_name='Tipo de Salud'),
        ),
    ]
